<?php echo Tag::javascriptInclude('formularios/frmActualizarTutorAcad.ui') ?>
<?php echo Tag::javascriptInclude('formularios/frmActualizarTutorAcad') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stDepartamento') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stDecanato') ?>
<?php echo Tag::javascriptMinifiedInclude('formularios/validaciones/validaciones') ?>
<?php echo Tag::javascriptInclude('jshash-2.2/md5') ?>

<DIV id="panel" ></DIV>

<script type='text/javascript'>
 		Ext.onReady(function() {
    		Ext.QuickTips.init();
    		var formActT = new frmActualizarTutorAcad({
        		renderTo: 'panel'
    	});
    		formActT.show();
		});
</script>
