<CENTER>
<H3
	style="font-size: 15px; color: #fff; font-family: Geneva, Arial, Helvetica, sans-serif;">RECURSOS
DISPONIBLES</H3>
</CENTER>
<BR>
<div
	style="font-size: 15px; color: #fff; font-family: Geneva, Arial, Helvetica, sans-serif;">
<table width="95%" align="center" class="gris">
	<tr>
		<td class="detalle">
		<p align="center"><?php echo Tag::linkTo("public/files/documentos/reglamentoPracticaProfesional.pdf","Reglamento Pr&aacute;ctica Profesional") ?>
		<BR>
		<?php echo Tag::linkTo("public/files/documentos/instructivoElaboracionInformePasantias.pdf","Instructivo Elaboraci&oacute;n Informe") ?>
		<BR>
		<?php echo Tag::linkTo("public/files/documentos/programaPracticaProfesional.pdf","Programa Pr&aacute;ctica Profesional") ?>
		<BR>
		<?php echo Tag::linkTo("public/files/documentos/formatoFichaDelPasante.pdf","Ficha del pasante") ?>
		<BR>
		<?php echo Tag::linkTo("public/files/documentos/planDeTrabajo.pdf","Plan de Trabajo") ?>
		<BR>
		<?php echo Tag::linkTo("public/files/documentos/formatoEvaluacionTutorEmpresarial.pdf","Formato Evaluaci&oacute;n Tutor Empresarial") ?>
		<BR>
		<?php echo Tag::linkTo("public/files/documentos/formatoEvaluacionTutorAcademico.pdf","Formato Evaluaci&oacute;n Tutor Academico") ?>
		<BR>
		<?php echo Tag::linkTo("public/files/documentos/formatoVisitasTutorAcademico.pdf","Formato de Visitas") ?>
		<BR>

		</p>
	
	</tr>
</table>


</div>
