<?php 
    if($noticia==false){
		echo("Lo sentimos, la noticia solicitada no puede ser encontrada.");
	}else{
		echo '<table width="95%" align="center"  class="gris">';
		echo '	<tr>
						<td class="titulo"> <B>'.$noticia['titulo'].'</B></td>
					</tr>
					<tr>
						<td class="detalle" > <p align="justify"> '.$noticia['contenido'].'</p></td>
					</tr>
					<tr >
						<td class="pie" > <B>Publicado el : </B> '.$noticia['fchPublicacion'].'
						 <B> por: </B>'.$noticia['nombre'].', '.$noticia['apellido'].'.</td>
					</tr>';	
		
		echo '</table>';
	}
	echo '<BR>'.Tag::linkTo('noticia','Regresar');
	

?>

	


