<?php echo Tag::javascriptInclude('formularios/frmActualizarTutorEmpresarial.ui') ?>
<?php echo Tag::javascriptInclude('formularios/frmActualizarTutorEmpresarial') ?>
<?php echo Tag::javascriptInclude('jshash-2.2/md5') ?>

<DIV id="panel" align="center"></DIV>

<script type='text/javascript'>
 		Ext.onReady(function() {
    		Ext.QuickTips.init();
    		var formActTE = new frmActualizarTutorEmpresarial({
        		renderTo: 'panel'
    	});
    		formActTE.show();
		});
</script>
