<?php
	echo Tag::javascriptMinifiedInclude('formularios/panelOferta.ui'); 
	echo Tag::javascriptMinifiedInclude('formularios/panelOferta');
	echo Tag::javascriptMinifiedInclude('formularios/frmVerOferta.ui'); 
	echo Tag::javascriptMinifiedInclude('formularios/frmVerOferta');
	echo Tag::javascriptMinifiedInclude('formularios/dataStore/stOfertasPasante') ;
?>

<script type='text/javascript'>
	Ext.onReady(function() {
    	Ext.QuickTips.init();
			var pOferta = new panelOferta({
        				renderTo: 'panel'
	   				 });
    	pOferta.show();
    	stOfertasPasante.load({params: {start: 0, limit: 10}}); 
	});
	
</script>

<DIV id='panel'></DIV>
<p  class="blanco" >
Seleccione una fila y luego la opci&oacute;n de la barra de men&uacute; del grid.
</p>