<?php
echo Tag::javascriptMinifiedInclude('formularios/validaciones/validaciones') ;
echo Tag::javascriptMinifiedInclude('formularios/frmCambiarClave.ui');
echo Tag::javascriptMinifiedInclude('formularios/frmCambiarClave');

?>

<DIV id="panel" align="center"></DIV>


<script type='text/javascript'>
Ext.onReady(function() {
 	 Ext.QuickTips.init();
	 var frmCClave = new frmCambiarClave({
   	renderTo: 'panel'
    });
	 frmCClave.show();
});

</script>