<?php echo Tag::javascriptInclude('formularios/panelGestionCoordinaciones.ui') ?>
<?php echo Tag::javascriptInclude('formularios/panelGestionCoordinaciones') ?>
<?php echo Tag::javascriptInclude('formularios/frmCoordinacion.ui') ?>
<?php echo Tag::javascriptInclude('formularios/frmCoordinacion') ?>
<?php echo Tag::javascriptInclude('formularios/frmActualizarCoordinacion.ui') ?>
<?php echo Tag::javascriptInclude('formularios/frmActualizarCoordinacion') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stCoordinacion') ?>
<?php echo Tag::javascriptInclude('ext-3.3.1/ux/SearchField') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stDecanato') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stEmpleadosDec') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stCoordinaciones') ?>
<?php echo Tag::javascriptInclude('jshash-2.2/md5') ?>


<script type='text/javascript'>
	Ext.onReady(function() {
    	Ext.QuickTips.init();
    	var decan = new panelGestionCoordinaciones({
        	renderTo: 'panel'
	    });
    	decan.show();
	});
	
</script>

<div id='panel'></div>
<p class="blanco" >
Seleccione una fila y luego la opci&oacute;n de la barra de men&uacute; del grid.
</p>