<?php echo Tag::javascriptInclude('formularios/panelGestionUniversidad.ui') ?>
<?php echo Tag::javascriptInclude('formularios/panelGestionUniversidad') ?>
<?php echo Tag::javascriptInclude('formularios/frmUniversidad.ui') ?>
<?php echo Tag::javascriptInclude('formularios/frmUniversidad') ?>
<?php echo Tag::javascriptInclude('formularios/frmActualizarUniversidad.ui') ?>
<?php echo Tag::javascriptInclude('formularios/frmActualizarUniversidad') ?>
<?php echo Tag::javascriptInclude('ext-3.3.1/ux/SearchField') ?>

<?php echo Tag::javascriptInclude('formularios/dataStore/stEstado') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stCiudad') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stUniversidadFull') ?>
<?php echo Tag::javascriptInclude('jshash-2.2/md5') ?>


<script type='text/javascript'>
	Ext.onReady(function() {
    	Ext.QuickTips.init();
    	var univer = new panelGestionUniversidad({
        	renderTo: 'panel'
	    });
    	univer.show();
	});
	
</script>

<div id='panel'></div>
<p class="blanco" >
Seleccione una fila y luego la opci&oacute;n de la barra de men&uacute; del grid.
</p>