<?php echo Tag::javascriptInclude('formularios/panelGestionTiposPasantia.ui') ?>
<?php echo Tag::javascriptInclude('formularios/panelGestionTiposPasantia') ?>
<?php echo Tag::javascriptInclude('formularios/frmTipoPasantia.ui') ?>
<?php echo Tag::javascriptInclude('formularios/frmTipoPasantia') ?>

<?php echo Tag::javascriptInclude('ext-3.3.1/ux/SearchField') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stTipoPasantia') ?>

<?php echo Tag::javascriptInclude('jshash-2.2/md5') ?>


<script type='text/javascript'>
	Ext.onReady(function() {
    	Ext.QuickTips.init();
    	var decan = new panelGestionTiposPasantia({
        	renderTo: 'panel'
	    });
    	decan.show();
	});
	
</script>

<div id='panel'></div>
<p class="blanco" >
Seleccione una fila y luego la opci&oacute;n de la barra de men&uacute; del grid.
</p>