<table width="100%">
	<tr>
		<td valign="top" width="20%" align="center" ><BR>
		<table align="center" >
			<tr>
				<td><?php 

				echo Tag::linkTo("registro/pasante",  Tag::image("imagesExperientia/pasante.png")) ;
				?></td>
			</tr>
			<tr>
				<td><?php 

				echo Tag::linkTo("registro/tutor",  Tag::image("imagesExperientia/tutor.png")) ;
				?></td>
			</tr>
			<tr>
				<td><?php 

				echo Tag::linkTo("registro/empresa",  Tag::image("imagesExperientia/empresa.png")) ;
				?></td>
			</tr>
		</table>
		</td>
		<td><?php View::getContent() ?></td>
	</tr>
</table>


