<table width="100%">
	<tr>
		<td valign="top" width="20%"><b>.::Registro de usuarios::.</b> <BR>
		<table width="100%">
			<tr>

			</tr>

			<tr>
				<td><?php 

				echo Tag::linkTo("#", Tag::image("imagesExperientia/users.png"));
				?></td>
			</tr>
			<tr>
				<td><?php 

				echo Tag::linkTo("registro/empresa",  Tag::image("imagesExperientia/company_256.png")) ;
				?></td>
			</tr>
		</table>
		</td>
		<td><?php View::getContent() ?></td>
	</tr>
</table>


