<?php
	echo Tag::javascriptInclude('formularios/panelGestionPasantes.ui'); 
	echo Tag::javascriptInclude('formularios/panelGestionPasantes'); 
	echo Tag::javascriptInclude('formularios/dataStore/stPasantes');
	echo Tag::javascriptInclude('formularios/dataStore/stCarreraLight');		
  ?>
<?php echo Tag::javascriptInclude('ext-3.3.1/ux/SearchField') ?>
<?php echo Tag::javascriptMinifiedInclude('formularios/frmVerPasante.ui');?>
<?php echo Tag::javascriptMinifiedInclude('formularios/frmVerPasante'); ?>
<?php echo Tag::javascriptMinifiedInclude('formularios/frmVerPasantia.ui');?>
<?php echo Tag::javascriptMinifiedInclude('formularios/frmVerPasantia'); ?>
<?php echo Tag::javascriptMinifiedInclude('formularios/frmNotificacion.ui');?>
<?php echo Tag::javascriptMinifiedInclude('formularios/frmNotificacion'); ?>

<?php echo Tag::javascriptInclude('formularios/frmPasantes.ui') ?>
<?php echo Tag::javascriptInclude('formularios/frmPasantes') ?>
<?php echo Tag::javascriptInclude('formularios/frmActualizarPasantes.ui') ?>
<?php echo Tag::javascriptInclude('formularios/frmActualizarPasantes') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stEstado') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stCiudad') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stDecanato') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stCarrera') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stSemestre') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stModalidadPasantia') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stTipoPasantia') ?>

<script type='text/javascript'>
Ext.onReady(function() {
 	 	 Ext.QuickTips.init();
    	 var pPasantes = new panelGestionPasantes({
        	renderTo: 'panel'
	     });
    	 pPasantes.show();
	 });
stPasantes.setBaseParam('pCarreraId','*');
stPasantes.load({params: {start: 0, limit: 10}});

</script>


<DIV id='panel'></DIV>
Seleccione una fila y luego la opci&oacute;n de la barra de men&uacute; del grid.
