<?php echo Tag::javascriptMinifiedInclude('formularios/frmPasantes.ui') ?>
<?php echo Tag::javascriptMinifiedInclude('formularios/frmPasantes') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stEstado') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stCiudad') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stDecanato') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stCarrera') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stSemestre') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stModalidadPasantia') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stTipoPasantia') ?>
<?php echo Tag::javascriptInclude('jshash-2.2/md5') ?>

<script type='text/javascript'>
 		Ext.onReady(function() {
    		Ext.QuickTips.init();
    		var formPas = new frmPasantes({
        		renderTo: Ext.getBody()
    	});
    		formPas.show();
		});
</script>
