<?php echo Tag::javascriptMinifiedInclude('formularios/frmPasantes.ui') ?>
<?php echo Tag::javascriptMinifiedInclude('formularios/frmPasantes') ?>
<?php echo Tag::javascriptMinifiedInclude('formularios/dataStore/stEstado') ?>
<?php echo Tag::javascriptMinifiedInclude('formularios/dataStore/stCiudad') ?>
<?php echo Tag::javascriptInclude('formularios/dataStore/stDecanato') ?>
<?php echo Tag::javascriptMinifiedInclude('formularios/dataStore/stCarrera') ?>
<?php echo Tag::javascriptMinifiedInclude('formularios/dataStore/stSemestre') ?>
<?php echo Tag::javascriptMinifiedInclude('formularios/dataStore/stTipoPasantia') ?>
<?php echo Tag::javascriptMinifiedInclude('formularios/dataStore/stModalidadPasantia') ?>
<?php echo Tag::javascriptMinifiedInclude('jshash-2.2/md5') ?>

<script type='text/javascript'>
 	Ext.onReady(function() {
    	Ext.QuickTips.init();
    	Ext.get('btnIniciarRegistroPasante').on('click', function(e){
    		var formPas = new frmPasantes({
        		renderTo: Ext.getBody()
    	});
    		formPas.show();
    	});
	});
</script>

<div class="textoRegistro"><b style="font-weight: bold;">Registro de
Pasantes</b> <br />
<BR>
Para registrarse como Pasante haga click en el siguiente bot&oacute;n: <BR>
<BR>
<button id="btnIniciarRegistroPasante" class="button">Registrar</button>
<BR>
<BR>
<P align="justify">Una vez registrado recibir&aacute; un correo
electr&oacute;nico en la direcc&oacute;n ingesada, para confirmar su
registro.</P>
</div>
