<?php echo Tag::javascriptInclude('formularios/frmConfirmacionTutorAcad.ui') ?>
<?php echo Tag::javascriptInclude('formularios/frmConfirmacionTutorAcad') ?>
<?php echo Tag::javascriptMinifiedInclude('jshash-2.2/md5') ?>


<script type='text/javascript'>
 		Ext.onReady(function() {
    		Ext.QuickTips.init();
    		var cmp1 = new frmConfirmacionTutorAcad({
        		renderTo: 'panel'
    	});
    	Ext.getCmp('txtHash').setValue('<?php echo $hash?>');
    	cmp1.show();
		});
 	
</script>
<div id='panel' align="center"></div>